### ISSUE TITLE
How did you test this?

### ISSUE THREAD

**Issue by muhajirdev** [fabe/gatsby-react-loadable#1]
I tried to reload a few time. `/` and `/without`. The `/without` one perceived faster.

**Comment by fabe** [comment]
Using Lighthouse Audits. Here's one I just did with and without:

###### With:
<img width="727" alt="screenshot 2018-10-02 09 55 05" src="https://user-images.githubusercontent.com/5220692/46335934-798c5980-c629-11e8-9c63-885bc194fb7f.png">

###### Without:
<img width="730" alt="screenshot 2018-10-02 09 55 29" src="https://user-images.githubusercontent.com/5220692/46335939-7b561d00-c629-11e8-8c80-535a636ef59d.png">

That's the impact of `moment` being loaded in (which isn't *that* much, it just shows that the code is indeed split). Thanks!

**Comment by muhajirdev** [comment]
Ah, I see. thanks man
